### ISSUE TITLE
Indexing two local folders

### ISSUE THREAD

**Issue by kolovos** [kb634/mondo-hawk#1]
I'm encountering some unwanted behaviour while using Hawk to index two different local folders. Steps to reproduce:

1. Create a new Hawk
2. Register the JDTAST.ecore metamodel with it
3. Create a folder (e.g. hawk-indexed)
4. Register the new folder with Hawk
5. Add set0.xmi to hawk-indexed
6. Run the following query against Hawk: TypeDeclaration.all.size().println();
7. Prints 13 in the console
8. Create a second folder (e.g. hawk-indexed-too)
9. Register the new folder with Hawk
10. Add set0.xmi to hawk-indexed-too
11. Run the same query again
12. Prints 13 again (should probably print 26 instead)

**Comment by bluezio** [comment]
This seems to be still happening. I'll investigate a bit more.

**Comment by bluezio** [comment]
It seems it was some problem in my personal setup. After cleaning up my workspaces it works fine: indexing just .../0/set0.xmi returns 14 elements, and indexing .../0/set0.xmi and .../0copy/set0.xmi returns 28. Closing.
